name: Build and Push Docker image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "23 13 3 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push container image amd64
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/l4r5/borgmatic:latest
        platforms: linux/amd64
        dockerfile_path: Dockerfile

    - name: Build and push container image armv7
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/l4r5/borgmatic:latest
        platforms: linux/arm/v7
        dockerfile_path: Dockerfile

    - name: Build and push container image arm64
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/l4r5/borgmatic:latest
        platforms: linux/arm64/v8
        dockerfile_path: Dockerfile

